#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f system.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace system.sv --exe system_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsystem.mk Vsystem

#run executable simulation file
obj_dir/Vsystem